name: Publish Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  publish_sphinx_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated version
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme myst_parser furo

      - name: Sphinx build
        run: |
          sphinx-build . ./_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated version
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          force_orphan: true
